id: '17296874645840.930355534003559'
kind: workflow
name: onAddAssetButtonClick
nameConfigured: true
steps:
  - id: '17296874736700.49975859927303934'
    type: customAsyncCode
    name: code
    params:
      - type: asyncCode
        value: ./code.js
        valueType: interpolatedValue
        interpolationType: code
    level: 0
    fallthroughError: false
    isChanged: true
mode: manual
modeConfigured: false
parentPageId: '1'
parentId: '17296874559840.39698328111392134'
config:
  shouldConfirm: false
  confirmMessage: >-
    Are you sure you'd like to proceed with
    "{{actions.onAddAssetButtonClick.name}}"?
  showSuccessToast: false
  successToast: Action "{{actions.onAddAssetButtonClick.name}}" successfully executed
  successToastDuration: '3000'
  successToastHideByClick: false
  showErrorToast: true
  errorToast: Action "{{actions.onAddAssetButtonClick.name}}" has failed
  errorToastDuration: '3000'
  errorToastHideByClick: false
  delay: '0'
  runWhenFirstReferenced: true
  preserveStateOnPageChange: false
selected: true
configured: true
